### ISSUE TITLE
Possible to wrap SpecialTextSpan with MouseRegion for cursor change on desktop?

### ISSUE THREAD

**Issue by seanmc86** [fluttercandies/extended_text#102]
I would like to migrate to this package and replace my existing TextSpan and WidgetSpan structure. However, the one thing I require that I didn't see possible, is if you can wrap SpecialTextSpan with MouseRegion somehow?

I tried using ExtendedTextSelectionPointerHandler and parsing the text values from ExtendedTextSelectionState, but when I wrapped ExtendedText with a MouseRegion, even after updating the state to be clickable it did not work.

I need to use SystemMouseCursors.click for special text spans.

**Comment by seanmc86** [comment]
I notice that the finishText() override method in SpecialText returns an InlineSpan. Is it safe to return a WidgetSpan for these types of special text spans? (Safe in terms of text layout relative to the other spans, as I know in the past using TextSpan and WidgetSpan together can be out of line)

**Comment by zmtzawqlp** [comment]
try widgetspan

**Comment by seanmc86** [comment]
I have tried WidgetSpan now. I have `selectionEnabled: true` in ExtendedText, but copying over text and a URL together gives me this:

Text written: "this is a link ￼https://www.google.com"
Clipboard output: "this is a link ￼<OBJ>" (shows an object symbol)

Should I be providing something else back to SpecialText so it knows which data to hand off when copied?

**Comment by zmtzawqlp** [comment]
Please set actualtext and take care of startindex

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2021年4月16日 21:50
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [fluttercandies/extended_text] Possible to wrap SpecialTextSpan with MouseRegion for cursor change on desktop? (#102)


I have tried WidgetSpan now. I have selectionEnabled: true in ExtendedText, but copying over text and a URL together gives me this:

Text written: "this is a link ￼https://www.google.com"
Clipboard output: "this is a link ￼" (shows an object symbol)

Should I be providing something else back to SpecialText so it knows which data to hand off when copied?
