### ISSUE TITLE
 flutter 2.2 adapt

### ISSUE THREAD

**Issue by wenboLee** [fluttercandies/extended_text#109]
flutter 2.2 的Api 有变动，适配一下？

**Comment by KuuBee** [comment]
类似的问题
flutter 环境
`Channel stable, 2.2.0, on macOS 11.3.1 20E241 darwin-x64, locale zh-Hans-CN`
异常
```
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running Xcode build...
Xcode build done.                                           17.7s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    ../../../dev/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text-6.0.6/lib/src/selection/extended_text_selection.dart:135:7: Error: The non-abstract class 'ExtendedTextSelectionState' is missing implementations for these members:
     - TextSelectionDelegate.userUpdateTextEditingValue
    Try to either
     - provide an implementation,
     - inherit an implementation from a superclass or mixin,
     - mark the class as abstract, or
     - provide a 'noSuchMethod' implementation.

    class ExtendedTextSelectionState extends State<ExtendedTextSelection>
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ../../../dev/flutter/packages/flutter/lib/src/services/text_input.dart:822:8: Context: 'TextSelectionDelegate.userUpdateTextEditingValue' is defined here.
      void userUpdateTextEditingValue(TextEditingValue value, SelectionChangedCause cause);
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ../../../dev/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text-6.0.6/lib/src/selection/extended_text_selection.dart:439:8: Error: The method 'ExtendedTextSelectionState.hideToolbar' has fewer positional arguments than those of overridden method 'TextSelectionDelegate.hideToolbar'.
      void hideToolbar() {
           ^
    ../../../dev/flutter/packages/flutter/lib/src/services/text_input.dart:829:8: Context: This is the overridden method ('hideToolbar').
      void hideToolbar([bool hideHandles = true]);
           ^

    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete
    warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the Runner editor. (in target 'Runner' from project 'Runner')
    /Users/kuubee/Desktop/self_porject/fontend/flutter_demo/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.5.99. (in target 'Flutter' from project 'Pods')

Could not build the application for the simulator.
Error launching application on iPhone 12 Pro Max.
```

**Comment by wenboLee** [comment]
感谢补充log，出问题后，就downgrade了。(￣▽￣)"

**Comment by Oklahomawhore** [comment]
> 感谢补充log，出问题后，就downgrade了。(￣▽￣)"

Downgrade 插件还是flutter...

**Comment by Oklahomawhore** [comment]
#110  写了个临时修复，不知道可不可行

**Comment by wenboLee** [comment]
flutter downgrade

**Comment by zmtzawqlp** [comment]
周末空了。更新下

**Comment by twovs** [comment]
Launching lib\main.dart on oppo r9 plustm a in debug mode...
Running Gradle task 'assembleDebug'...
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text-6.0.6/lib/src/selection/extended_text_selection.dart:135:7: Error: The non-abstract class 'ExtendedTextSelectionState' is missing implementations for these members:
 - TextSelectionDelegate.userUpdateTextEditingValue
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ExtendedTextSelectionState extends State<ExtendedTextSelection>
      ^^^^^^^^^^^^^^^^^^^^^^^^^^
/D:/flutter/packages/flutter/lib/src/services/text_input.dart:822:8: Context: 'TextSelectionDelegate.userUpdateTextEditingValue' is defined here.
  void userUpdateTextEditingValue(TextEditingValue value, SelectionChangedCause cause);
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text-6.0.6/lib/src/selection/extended_text_selection.dart:439:8: Error: The method 'ExtendedTextSelectionState.hideToolbar' has fewer positional arguments than those of overridden method 'TextSelectionDelegate.hideToolbar'.
  void hideToolbar() {
       ^
/D:/flutter/packages/flutter/lib/src/services/text_input.dart:829:8: Context: This is the overridden method ('hideToolbar').
  void hideToolbar([bool hideHandles = true]);
       ^


FAILURE: Build failed with an exception.

* Where:
Script 'D:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1035

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'D:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 58s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by twovs** [comment]
https://github.com/fluttercandies/extended_text/pull/110/commits/6311107e112fdc858d9ab8b44b901da04df74bd1#diff-44f1aff42b2bac52d093b4e18fdeb94424794d49ff7571f4e039639d244a4cff

可行

**Comment by zmtzawqlp** [comment]
i will do later, it has much code to merge

**Comment by anhvu-sg** [comment]
just a question, when will your release the next version @zmtzawqlp ? :)

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_text/commit/9857c658f477116376cc37f36c298e37a8431f3c
