### ISSUE TITLE
在flutter 2.2.0下报错，和text_input.dart下的hideToolbar方法冲突

### ISSUE THREAD

**Issue by liaoyu1992** [fluttercandies/extended_text#111]
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text-6.0.6/lib/src/selection/extended_text_selection.dart:439:8: Error: The method 'ExtendedTextSelectionState.hideToolbar' has fewer positional arguments than those of overridden method 'TextSelectionDelegate.hideToolbar'.
  void hideToolbar() {
       ^
/D:/flutter/packages/flutter/lib/src/services/text_input.dart:829:8: Context: This is the overridden method ('hideToolbar').
  void hideToolbar([bool hideHandles = true]);

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_text/issues/109
