### ISSUE TITLE
text selection support 选择文本后复制粘贴区域不匹配

### ISSUE THREAD

**Issue by lyxia** [fluttercandies/extended_text#113]
例如：
hello world!
选择：
o w
ctrl+c后
ctrl+v后:
期望结果为：
o w
实际结果为：
llo

flutter版本为：2.2.3

**Comment by lyxia** [comment]
运行 example 中的 text selection support demo 必现。

**Comment by zmtzawqlp** [comment]
你应该提供完整的demo，或者好好看看readme先

**Comment by zmtzawqlp** [comment]
demo merge 出错，请更新最新的demo

https://github.com/fluttercandies/extended_text/commit/1fee23aedb8b5593a1e362d297f808a20da2bfc8
