### ISSUE TITLE
[Help]FocusNode problem

### ISSUE THREAD

**Issue by tiennv597** [fluttercandies/extended_text#115]
Can you please help me to add FocusNode parameter? Or can you guide me how to unfocus when clicking outside the text. Looking forward to hearing from you.
```
ExtendedText(
      'text',
       selectionEnabled: true,
       focusNode: focusNode,
 )
```

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_text/blob/c4c4969007aadd56c8c7898f0ed8d9c572b7e29f/example/lib/pages/text_selection_demo.dart#L113
