### ISSUE TITLE
7.0.0  Error: The non-abstract class 'ExtendedTextSelectionState' is missing implementations for these members:  - TextSelectionDelegate.copySelection  - TextSelectionDelegate.cutSelection  - TextSelectionDelegate.pasteText  - TextSelectionDelegate.selectAll Try to either  - provide an implementation,  - inherit an implementation from a superclass or mixin,  - mark the class as abstract, or  - provide a 'noSuchMethod' implementation.

### ISSUE THREAD

**Issue by liu1070832898** [fluttercandies/extended_text#116]
![image](https://user-images.githubusercontent.com/29189440/131311908-7811d44e-6864-4b38-ab0c-a69b4b3979ce.png)

**Comment by gfb-47** [comment]
Same error

**Comment by gfb-47** [comment]
Just solved, I forgot to update pusbpec.yaml

![Screen Shot 2022-02-21 at 10 40 16](https://user-images.githubusercontent.com/46033500/154966231-aca86b24-b65b-422c-98e7-375d0bdd13e1.png)

Also, deleting pubspec.lock might help.

**Comment by zmtzawqlp** [comment]
find the version that suit to your flutter sdk, thanks
