### ISSUE TITLE
overflowWidget感觉像溢出了，背景色变全黑

### ISSUE THREAD

**Issue by 7ye** [fluttercandies/extended_text#118]
![P S)0W ~8_K6U_EBKE5T_%P](https://user-images.githubusercontent.com/10414777/133963920-b1b6664b-4896-4c50-bb13-e191914a0495.png)
内容中间加了一个使用BackdropFilter做文字模糊的效果，只要加了这个，全文越界显示那儿肯定会直接变黑

**Comment by zmtzawqlp** [comment]
提供最简单的demo

**Comment by 7ye** [comment]
`class BlurTest extends StatefulWidget {
  
  const BlurTest({Key key}) : super(key: key);

  @override
  _BlurTestState createState() => _BlurTestState();
}

class _BlurTestState extends State<BlurTest> {

  @override
  Widget build(BuildContext context) {

    String description2 = "这是一段很长很长的文字，如果文字里有两个美元符号出现的话，那么从此符号开始后开始文字遮罩，\$\$，需求是用户发布一条朋友圈，想指定一个点开始后面的内容全隐藏，想看的人付费就可以看到隐藏的文字了。";
    String description1 = "这是一段完全开放的文字，他是完全正常的，他是完全正常的，因为他没有遮罩没有使用到BackdropFilter，所以这个TextOverflowWidget能正常显示全文";

    return Scaffold(
      appBar: AppBar(
        title: Text('文字模糊效果'),
        centerTitle: true,
      ),
      body: Padding(
        padding: EdgeInsets.all(16.0),
        child: Column(
          children: [
            ExtendedText(
                description1,
                style: TextStyle(fontSize: 16.0, color: Color(0xFF323232)),
                maxLines: 3,
                overflow: TextOverflow.ellipsis,
                overflowWidget: TextOverflowWidget(
                    align: TextOverflowAlign.right,
                    child: Row(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        const Text('...', style: TextStyle(fontSize: 16.0)),
                        const Text('全文', style: TextStyle(fontSize: 16.0, color: Color(0xFF005FCC))),
                      ],
                    )
                ),
                specialTextSpanBuilder:  MySpecialTextSpanBuilder()
            ),
            SizedBox(height: 20),
            ExtendedText(
                description2,
                style: TextStyle(fontSize: 16.0, color: Color(0xFF323232)),
                maxLines: 3,
                overflow: TextOverflow.ellipsis,
                overflowWidget: TextOverflowWidget(
                    align: TextOverflowAlign.right,
                    child: Row(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        const Text('...', style: TextStyle(fontSize: 16.0)),
                        const Text('全文', style: TextStyle(fontSize: 16.0, color: Color(0xFF005FCC))),
                      ],
                    )
                ),
                specialTextSpanBuilder:  MySpecialTextSpanBuilder()
            )
          ],
        ),
      )
    );
  }
}`

**Comment by 7ye** [comment]
`
class BlurTest extends StatefulWidget {
  
  const BlurTest({Key key}) : super(key: key);

  @override
  _BlurTestState createState() => _BlurTestState();
}

class _BlurTestState extends State<BlurTest> {

  @override
  Widget build(BuildContext context) {

    String description2 = "这是一段很长很长的文字，如果文字里有两个美元符号出现的话，那么从此符号开始后开始文字遮罩，\$\$，需求是用户发布一条朋友圈，想指定一个点开始后面的内容全隐藏，想看的人付费就可以看到隐藏的文字了。";
    String description1 = "这是一段完全开放的文字，他是完全正常的，他是完全正常的，因为他没有遮罩没有使用到BackdropFilter，所以这个TextOverflowWidget能正常显示全文";

    return Scaffold(
      appBar: AppBar(
        title: Text('文字模糊效果'),
        centerTitle: true,
      ),
      body: Padding(
        padding: EdgeInsets.all(16.0),
        child: Column(
          children: [
            ExtendedText(
                description1,
                style: TextStyle(fontSize: 16.0, color: Color(0xFF323232)),
                maxLines: 3,
                overflow: TextOverflow.ellipsis,
                overflowWidget: TextOverflowWidget(
                    align: TextOverflowAlign.right,
                    child: Row(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        const Text('...', style: TextStyle(fontSize: 16.0)),
                        const Text('全文', style: TextStyle(fontSize: 16.0, color: Color(0xFF005FCC))),
                      ],
                    )
                ),
                specialTextSpanBuilder:  MySpecialTextSpanBuilder()
            ),
            SizedBox(height: 20),
            ExtendedText(
                description2,
                style: TextStyle(fontSize: 16.0, color: Color(0xFF323232)),
                maxLines: 3,
                overflow: TextOverflow.ellipsis,
                overflowWidget: TextOverflowWidget(
                    align: TextOverflowAlign.right,
                    child: Row(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        const Text('...', style: TextStyle(fontSize: 16.0)),
                        const Text('全文', style: TextStyle(fontSize: 16.0, color: Color(0xFF005FCC))),
                      ],
                    )
                ),
                specialTextSpanBuilder:  MySpecialTextSpanBuilder()
            )
          ],
        ),
      )
    );
  }
}

`




`

/// SpecialTextSpanBuilder
class MySpecialTextSpanBuilder extends SpecialTextSpanBuilder {

  @override
  TextSpan build(String data, {TextStyle textStyle, onTap}) {
    var textSpan = super.build(data, textStyle: textStyle, onTap: onTap);
    //拦截内容，把遮罩内容后的文字颜色改变
    if(textSpan.children != null && textSpan.children.length == 3) {
      String maskText = textSpan.children[2].toPlainText();
      List<String> maskTextList = maskText.split('');
      //替换旧的TextSpan
      textSpan.children[2] = TextSpan(
        children: List.generate(maskTextList.length, (index) {
          return WidgetSpan(
            child: Stack(
              children: [
                Text(maskTextList[index], style: TextStyle(fontSize: 16.0, color: Color(0xFF3E3E3E))),
                Positioned(
                  top: 0,
                  bottom: 0,
                  left: 0,
                  right: 0,
                  child: ClipRRect(
                    child: BackdropFilter(
                      filter: ImageFilter.blur(sigmaX: 3, sigmaY: 3),
                      child: Container(
                          color: Colors.white.withAlpha(0)
                      ),
                    )
                  )
                ),
              ],
            )
          );
        })
      );
    }
    return textSpan;
  }

  @override
  SpecialText createSpecialText(String flag, {TextStyle textStyle, SpecialTextGestureTapCallback onTap, int index}) {
    if (flag == null || flag == "") {
      return null;
    }
    /// index is end index of start flag, so text start index should be index-(flag.length-1)
    if (isStart(flag, AtText.StartFlag)) {
      var atText = AtText(textStyle, onTap,
        start: 0 - (AtText.StartFlag.length - 1),
      );
      return atText;
    }
    return null;
  }
}

`


`

/// SpecialText
class AtText extends SpecialText {

  static const String StartFlag = "\$";
  static const String EndFlag = "\$";
  final int start;

  AtText(TextStyle textStyle, SpecialTextGestureTapCallback onTap,
    {this.start}
  ) : super(StartFlag, EndFlag, textStyle, onTap: onTap);

  @override
  TextSpan finishText() {
    TextStyle textStyle = this.textStyle?.copyWith(color: Colors.blue, fontSize: 16.0);
    return BackgroundTextSpan(
      background: Paint()..color = Colors.blue.withOpacity(0.15),
      text: '',
      style: textStyle,
    );
  }
}


`

**Comment by 7ye** [comment]
[blur_test.txt](https://github.com/fluttercandies/extended_text/files/7197219/blur_test.txt)

**Comment by zmtzawqlp** [comment]
因为对这部分做了 clip，用了 BlendMode.clear 方法，高模糊+这部分就变成了黑色

**Comment by zmtzawqlp** [comment]
你可以利用下面代码，为想要高斯模糊的文本添加 

 ``` dart
    style: TextStyle(
                    // color: Colors.black,
                    foreground: Paint()
                      ..maskFilter = MaskFilter.blur(BlurStyle.normal, 3.0)
                      ..color = Colors.black,
                  ),
```
