### ISSUE TITLE
ExtendedText 中进行文本选择，selectionHeightStyle属性无效

### ISSUE THREAD

**Issue by LCD27** [fluttercandies/extended_text#120]
版本:7.0.0,
用法:ExtendedText(
        “我这是内容，进行长按复制，文本高度没有对齐，you look look，11111”,
        onSpecialTextTap: (dynamic parameter) {},
        selectionHeightStyle: ui.BoxHeightStyle.strut,
        selectionColor: Colors.red,
        dragStartBehavior: DragStartBehavior.start,
        selectionEnabled: true,
      )

**Comment by jiang111** [comment]
#122  看这个issue,可以解决这个问题

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_text/commit/06548d5d9bddd96cc3575538951c402fc9101473
