### ISSUE TITLE
文本选择时高度不对齐,很难看,建议优化指定代码

### ISSUE THREAD

**Issue by jiang111** [fluttercandies/extended_text#122]
建议修改 extended_render_paragraph.dart 类中的 _paintSelection  方法

_selectionRects ??= _textPainter.getBoxesForSelection(actualSelection,boxHeightStyle: ui.BoxHeightStyle.max);

boxHeightStyle: ui.BoxHeightStyle.max 添加这个属性,不然的话,选择文本时中英文和widgetspan各种嵌套的时候文本高度不对齐,很难看

**Comment by jiang111** [comment]
也可以将传递过来的 selectionHeightStyle 参数带进去

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_text/commit/06548d5d9bddd96cc3575538951c402fc9101473
