### ISSUE TITLE
ExtendedText  style 设置字体大小后 overflowWidget 不显示

### ISSUE THREAD

**Issue by zhanglijie5997** [fluttercandies/extended_text#123]
`ExtendedText(
                    "Coupons can be used only if this condition is me",
                    maxLines: 2,
                    style: Theme.of(context).textTheme.caption?.copyWith(
                      fontSize: 35.w
                    ),
                    overflow: TextOverflow.ellipsis,
                    overflowWidget: TextOverflowWidget(
                      position: TextOverflowPosition.end,
                      align: TextOverflowAlign.center,
                      // just for debug
                      // debugOverflowRectColor: Colors.red.withOpacity(0.1),
                      child: Container(
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          children: <Widget>[
                            Text('\u2026 ', style: Theme.of(context).textTheme.caption?.copyWith(
                              // fontSize: 35.w
                            ),),
                            InkWell(
                              child: const Text(
                                'more',
                                style: TextStyle(
                                  color: Colors.red
                                ),
                              ),
                              onTap: () {
                                // launch(
                                //     'https://github.com/fluttercandies/extended_text');
                              },
                            )
                          ],
                        ),
                      ),
                    ),
                  )`

`
flutter :  2.5.0
extended_text : 7.0.0
`

**Comment by zmtzawqlp** [comment]
请使用最新版本试试
