### ISSUE TITLE
Chrome Breaking for Mixin: TextEditingActionTarget

### ISSUE THREAD

**Issue by ngocatfika** [fluttercandies/extended_text#124]
Hello, there is a breakage with the TextEditingAction target. Here is the error I am getting:

```
Running "flutter pub get" in hatch_success_flutter...
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
../../../../../.pub-cache/hosted/pub.dartlang.org/extended_text-8.0.2/lib/src/selection/extended_text_selection.dart:136:10: Error: Type 'TextEditingActionTarget' not found.
    with TextEditingActionTarget
         ^^^^^^^^^^^^^^^^^^^^^^^
../../../../../.pub-cache/hosted/pub.dartlang.org/extended_text-8.0.2/lib/src/selection/extended_text_selection.dart:135:7: Error: The type 'TextEditingActionTarget' can't be mixed in.
class ExtendedTextSelectionState extends State<ExtendedTextSelection>
      ^
Failed to compile application.

```

Not sure how to fix this. This is when I tried to compile for web. Any pointers would be great!

**Comment by zmtzawqlp** [comment]
flutter sdk version

**Comment by ngocatfika** [comment]
The Flutter SDK version I am using is Flutter 2.9.0-0.1.pre:

[✓] Flutter (Channel beta, 2.9.0-0.1.pre, on macOS 12.0.1 21A559 darwin-x64, locale en-US)
    • Flutter version 2.9.0-0.1.pre at 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8f1f9c10f0 (3 weeks ago), 2021-12-14 13:41:48 -0800
    • Engine revision 234aca678a
    • Dart version 2.16.0 (build 2.16.0-80.1.beta)
    • DevTools version 2.9.1

**Comment by zmtzawqlp** [comment]
just support stable version of flutter

**Comment by jonataslaw** [comment]
This error is in stable now

**Comment by zhileichen** [comment]
`TextEditingActionTarget` removed in this pr https://github.com/flutter/flutter/pull/90684

**Comment by zmtzawqlp** [comment]
> `TextEditingActionTarget` removed in this pr [flutter/flutter#90684](https://github.com/flutter/flutter/pull/90684)

I will update them later， thanks

**Comment by zmtzawqlp** [comment]
10.0.0 is ready.

**Comment by Esdeath** [comment]
> 10.0.0 is ready.

9.0.0 ?

**Comment by Esdeath** [comment]
> 10.0.0 is ready.

9.0.0 ?

**Comment by zmtzawqlp** [comment]
> > 10.0.0 is ready.
> 
> 9.0.0 ?

yes, it's 9.0.0
