### ISSUE TITLE
Flutter 2.0.0 extended_text: ^4.0.0   extended_text_library: 4.0.0 出现错误

### ISSUE THREAD

**Issue by baseSky** [fluttercandies/extended_text#125]
/Users/hfy/Desktop/tool/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text_library-4.0.0/lib/src/selection/cupertino_text_selection_controls.dart:483:10: Error: The method 'ExtendedCupertinoTextSelectionControls.buildToolbar' has fewer positional arguments than those of overridden method 'TextSelectionControls.buildToolbar'.
  Widget buildToolbar(
         ^
/Users/hfy/Desktop/tool/flutter/packages/flutter/lib/src/widgets/text_selection.dart:137:10: Context: This is the overridden method ('buildToolbar').
  Widget buildToolbar(
         ^
/Users/hfy/Desktop/tool/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text_library-4.0.0/lib/src/selection/material_text_selection_controls.dart:762:10: Error: The method 'ExtendedMaterialTextSelectionControls.buildToolbar' has fewer positional arguments than those of overridden method 'TextSelectionControls.buildToolbar'.
  Widget buildToolbar(
         ^
/Users/hfy/Desktop/tool/flutter/packages/flutter/lib/src/widgets/text_selection.dart:137:10: Context: This is the overridden method ('buildToolbar').
  Widget buildToolbar(
         ^
/Users/hfy/Desktop/tool/flutter/.pub-cache/hosted/pub.flutter-io.cn/get-3.10.0/lib/src/navigation/extension_navigation.dart:461:37: Error: No named parameter with the name 'shadowThemeOnly'.
    final theme = Theme.of(context, shadowThemeOnly: true);
                                    ^^^^^^^^^^^^^^^
/Users/hfy/Desktop/tool/flutter/packages/flutter/lib/src/material/theme.dart:107:20: Context: Found this candidate, but the arguments don't match.
  static ThemeData of(BuildContext context) {
                   ^^
/Users/hfy/Desktop/tool/flutter/.pub-cache/hosted/pub.flutter-io.cn/get-3.10.0/lib/src/navigation/extension_navigation.dart:648:43: Error: No named parameter with the name 'shadowThemeOnly'.
      theme: Theme.of(key.currentContext, shadowThemeOnly: true),
                                          ^^^^^^^^^^^^^^^
/Users/hfy/Desktop/tool/flutter/packages/flutter/lib/src/material/theme.dart:107:20: Context: Found this candidate, but the arguments don't match.
  static ThemeData of(BuildContext context) {
                   ^^
/Users/hfy/Desktop/tool/flutter/.pub-cache/hosted/pub.flutter-io.cn/city_pickers-0.2.0/lib/src/cities_selector/cities_selector.dart:415:9: Error: No named parameter with the name 'resizeToAvoidBottomPadding'.
        resizeToAvoidBottomPadding: false,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
/Users/hfy/Desktop/tool/flutter/packages/flutter/lib/src/material/scaffold.dart:1451:9: Context: Found this candidate, but the arguments don't match.
  const Scaffold({
        ^^^^^^^^
/Users/hfy/Desktop/tool/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text_library-4.0.0/lib/src/selection/extended_text_selection_overlay.dart:348:46: Error: Too few positional arguments: 8 required, 7 given.
        child: selectionControls.buildToolbar(
                                             ^
/Users/hfy/Desktop/tool/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text-4.0.0/lib/src/extended_rich_text.dart:162:13: Error: No named parameter with the name 'nullOk'.
            nullOk: true,
            ^^^^^^
/Users/hfy/Desktop/tool/flutter/packages/flutter/lib/src/widgets/localizations.dart:413:17: Context: Found this candidate, but the arguments don't match.
  static Locale localeOf(BuildContext context) {
                ^^^^^^^^
/Users/hfy/Desktop/tool/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text-4.0.0/lib/src/extended_rich_text.dart:190:60: Error: No named parameter with the name 'nullOk'.
      ..locale = locale ?? Localizations.localeOf(context, nullOk: true)

**Comment by zmtzawqlp** [comment]
查看changlog。 看看2.0.0适配的是多少版本。然后写死版本号

**Comment by zmtzawqlp** [comment]
查看changlog。 看看2.0.0适配的是多少版本。然后写死版本号
