### ISSUE TITLE
After drag the text then right-click the mouse, but the selected area will change

### ISSUE THREAD

**Issue by chifandeyu** [fluttercandies/extended_text#129]
https://user-images.githubusercontent.com/15946864/172988706-2a1a26e2-3cb2-4b5b-99a2-ee31159eff33.mp4
Drag the mouse from right to left to reproduce.

**Comment by chifandeyu** [comment]
目前从左到右选中文字右击，也偶现右击后选中区域会变

https://user-images.githubusercontent.com/15946864/173778940-9dd49cc0-fe6f-4a5e-868c-e98303ba08bc.mp4

**Comment by zmtzawqlp** [comment]
in fact, toolbar should be not shown on desktop as flutter design. i make some changes, you can see what happen on official SelectableText

**Comment by zmtzawqlp** [comment]
please check it on lastest version, reopen if need.
