### ISSUE TITLE
ExtendedText开启selection报错

### ISSUE THREAD

**Issue by wang642357** [fluttercandies/extended_text#133]
在listview中使用ExtendedText，selectionEnabled = true，长按显示toolbar后退出再进就会报错
![image](https://user-images.githubusercontent.com/20984545/184582286-b556c5ff-6ab7-4fa7-b3fd-436620fa6820.png)

**Comment by zmtzawqlp** [comment]
9.1.2试试看

**Comment by zmtzawqlp** [comment]
请使用最新的版本
