### ISSUE TITLE
CustomTextOverFlow 在iOS上没有对齐

### ISSUE THREAD

**Issue by lyb5834** [fluttercandies/extended_text#134]
版本：`9.1.2`
平台：`iOS`
问题描述：当显示的文字是**中文**时，`CustomTextOverFlow`并没有和文字对齐，明显文字偏下了一点，**Android**上是正常的。
问题复现图：![(demo图)](https://testv2.storage.shmedia.tech/d9597b9698294f13944a9685e1b14ae9.jpg?imageslim)

**Comment by zmtzawqlp** [comment]
设置 textstyle height

**Comment by lyb5834** [comment]
> 

这个确实有用，设置 `height = 1.3` 时，最接近和文字对齐，但是这个很反直觉并且`Android` 上又往下偏移了，需要分开设置额？

**Comment by zmtzawqlp** [comment]
嗯。文字这东西。很玄学

**Comment by lyb5834** [comment]
好的，那这个问题就这样吧。
