### ISSUE TITLE
Flutter 3.7 Error: The non-abstract class 'ExtendedTextSelectionState' is missing implementations for these members:

### ISSUE THREAD

**Issue by bugrevealingbme** [fluttercandies/extended_text#137]
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
: Error: The non-abstract class 'ExtendedTextSelectionState' is missing implementations for these members:
 - TextInputClient.didChangeInputControl
 - TextInputClient.performSelector

Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ExtendedTextSelectionState extends State<ExtendedTextSelection>
      ^^^^^^^^^^^^^^^^^^^^^^^^^^
: Context: 'TextInputClient.didChangeInputControl' is defined here.
  void didChangeInputControl(TextInputControl? oldControl, TextInputControl? newControl) {}
       ^^^^^^^^^^^^^^^^^^^^^
: Context: 'TextInputClient.performSelector' is defined here.
  void performSelector(String selectorName) {}
       ^^^^^^^^^^^^^^^

: Error: Too few positional arguments: 4 required, 3 given.
        return BallisticScrollActivity(this, simulation, context.vsync);
                                      ^
: Context: Found this candidate, but the arguments don't match.
  BallisticScrollActivity(
  ^^^^^^^^^^^^^^^^^^^^^^^
: Error: Too few positional arguments: 4 required, 3 given.
  ) : super(position, simulation, vsync);
           ^
: Error: Too few positional arguments: 4 required, 3 given.
        super(position, simulation, vsync);

             ^
: Error: The method 'FocusTrapArea' isn't defined for the class '_PinputState'.
- '_PinputState' is from 'package:pinput/src/pinput.dart' ('../../.pub-cache/hosted/pub.dev/pinput-2.2.21/lib/src/pinput.dart').
Try correcting the name to the name of an existing method, or defining a method named 'FocusTrapArea'.
      child: FocusTrapArea(
             ^^^^^^^^^^^^^

Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* Where:
Script '/Users/bmerdogan/FlutterDev/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1151

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/bmerdogan/FlutterDev/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
BUİLD FAILED in 13s
Exception: Gradle task assembleDebug failed with exit code 1
Exited

**Comment by jonbhanson** [comment]
I also received this error after upgrading to Flutter 3.7.

**Comment by mumenma** [comment]
Please

**Comment by bugrevealingbme** [comment]
Use like this:

  extended_text:
    git:
      url: https://github.com/LOCKEDFILE/extended_text

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_text/commit/5714918f6b05e670bf26c1437b0c139a4708015c
