### ISSUE TITLE
ios不支持长按选择

### ISSUE THREAD

**Issue by git-maven** [fluttercandies/extended_text#141]
### Platforms

iOS

### Description

请问现在ios支持长按选择嘛
我用官方的SelectableText是支持了,但是官方的有个问题就是, 点击空白处不会自动取消选择, 只有ExtendText实现了, 但是现在ExtendText不支持长按选择, 在使用ExtendText.rich的时候, 有一些链接需要单击跳转, 这时候就有冲突了

**Comment by git-maven** [comment]
![image](https://user-images.githubusercontent.com/45022397/235051875-ced2cfae-17ba-4171-ac9e-fe92119b7d4d.png)
设置成android的目标主题就可以了

**Comment by zmtzawqlp** [comment]
系统默认行为
