### ISSUE TITLE
[Feature request] 

### ISSUE THREAD

**Issue by jonnyjohnson1** [fluttercandies/extended_text#148]
### Platforms

Android, iOS, macOS, Web, Windows, Linux

### Description

I'd love to see the draw line end at the end of the text, and not at the end of the container.

This is the current view:
<img width="231" alt="Screenshot 2023-06-24 at 8 32 47 AM" src="https://github.com/fluttercandies/extended_text/assets/32085184/3093ea05-3ada-4134-aa0e-c506709ea1e9">

It seems like it has to do with updating the value of rect.right to match the value of the last character on the line, but I am not finding that.

```
///top-right
            if (endOffset != null) {
              final Rect firstLineRect =
                  offset & Size(rect.right - offset.dx, painter.height);

              if (backgroundTextSpan.clipBorderRadius != null) {
                canvas.save();
                canvas.clipPath(Path()
                  ..addRRect(backgroundTextSpan.clipBorderRadius!
                      .resolve(painter.textDirection)
                      .toRRect(firstLineRect)));
              }
```

The value from the textRect, extends all the way to the end of the container, and doesn't just get to the end of the characters.

```
final Rect textRect = offset & painter!.size;
```

### Why

This is a detail that better matches what is expected. Someone reading wants to see the highlighted text.

**Comment by zmtzawqlp** [comment]
you can use BackgroundTextSpan
