### ISSUE TITLE
[Feature request] 希望能扩展一个展开/收起文本的功能

### ISSUE THREAD

**Issue by chenjiangmin126** [fluttercandies/extended_text#149]
### Platforms

dart

### Description

请求扩展一个展开更多 和收起的功能。
目前使用overflowWidget 可以自定义溢出的widget。 
可以自己实现点击展开文本 ，但是没办法再次收起来。 
希望能扩展一个样的功能。 在一些列表中的文本经常会使用到。 

### Why

<img width="299" alt="image" src="https://github.com/fluttercandies/extended_text/assets/108910351/a9ca38dc-7445-4dc9-a3a0-cefc9241d653">

**Comment by zmtzawqlp** [comment]
这个可以自己写，展开之后。在尾部添加一个 收起的按钮就行了
