### ISSUE TITLE
[Feature request] Custom text to show read more text 

### ISSUE THREAD

**Issue by maxakak1998** [fluttercandies/extended_text#150]
### Platforms

dart, Android, iOS

### Description

Can we do the feature that show/hide the text like this ?

![image](https://github.com/fluttercandies/extended_text/assets/50696626/6f0ea106-bc00-464f-b829-97368abcd421)

### Why

When the text is so long, we can shorten it with the Read more text in the end

**Comment by zmtzawqlp** [comment]
It's very easy to do like that, and not plan to add this function into ExtendedText

**Comment by maxakak1998** [comment]
> It's very easy to do like that, and not plan to add this function into ExtendedText

Can you instruct how to do that? Many thanks
