### ISSUE TITLE
换行存在问题

### ISSUE THREAD

**Issue by xiaobt** [fluttercandies/extended_text#16]
存在的问题是一行空间还没有占满就换行了
这是布局代码
`///第一行
  Widget oneRow() {
    final List<TextSpan> textSpanList = List();
    final positionNameSpan = TextSpan(
      text: "服务端C++架构师服务端C++架构师",
      style: TextStyle(
        fontSize: 18,
        fontWeight: FontWeight.bold,
        color: ZPMColors.ZP_28,
      ),
    );
    textSpanList.add(positionNameSpan);

    if (this.position.chatWindow > 0) {
      final youliaoSpan = ImageSpan(
        AssetImage(
            "lib/src/screens/positionGroup/resources/icon_pos_youliao.png"),
        imageWidth: 44,
        imageHeight: 19,
        fit: BoxFit.contain,
        margin: const EdgeInsets.fromLTRB(6, 2, 0, 2)
      );
      textSpanList.add(youliaoSpan);
    }

    if (this.position.positionSourceType == 2) {
      final netApplySpan = ImageSpan(
        AssetImage(
            "lib/src/screens/positionGroup/resources/icon_pos_netapply.png"),
        imageWidth: 26,
        imageHeight: 14,
        fit: BoxFit.contain,
        margin: const EdgeInsets.fromLTRB(6, 2, 0, 4)
      );
      textSpanList.add(netApplySpan);
    }

    return ExtendedText.rich(
      TextSpan(children: textSpanList),
      maxLines: 2,
      textAlign: TextAlign.left,
      overflow: ExtendedTextOverflow.ellipsis,
    );
  }`
![屏幕快照 2019-06-18 下午5 30 52](https://user-images.githubusercontent.com/7822738/59670799-165e4980-91ef-11e9-95e9-8eabc7cd5120.png)

**Comment by zmtzawqlp** [comment]
这个是官方TextPainter的问题。。可以去给官方提一下
