### ISSUE TITLE
Building AOT snapshot in release mode (ios-release)...                Compiler message:      lib/special_text/emoji_text.dart:22:14: Error: A value of type 'ImageSpan' can't be assigned to a     variable of type 'TextSpan'.

### ISSUE THREAD

**Issue by vikashfleapo2019** [fluttercandies/extended_text#24]
- 'ImageSpan' is from 'package:extended_text_library/src/image_span.dart'
     ('file://Development/flutter/.pub-cache/hosted/pub.dartlang.org/extended_text_library-0.
     4.2/lib/src/image_span.dart').

     - 'TextSpan' is from 'package:flutter/src/painting/text_span.dart'
     ('file:/Development/flutter/packages/flutter/lib/src/painting/text_span.dart').

    Try changing the type of the left hand side, or casting the right hand side to 'TextSpan'.

          return ImageSpan(AssetImage(EmojiUitl.instance.emojiMap[key]),

**Comment by zmtzawqlp** [comment]
can you provide full error msg, and the demo to produce this issue

**Comment by zmtzawqlp** [comment]
@vikashfleapo2019 please take a look ， v0.6.3

**Comment by CSystem** [comment]
> @vikashfleapo2019 please take a look ， v0.6.3

it`s not work,the same error

**Comment by CSystem** [comment]
@zmtzawqlp it`s not work,the same error
