### ISSUE TITLE
Ability to load and save over network as JSON

### ISSUE THREAD

**Issue by gedw99** [fluttercandies/extended_text#25]
I could not find a model file to extend this to allow data changes to be saved and loaded as JSON.

Could you explain if this is supported ?

**Comment by Evsio0n** [comment]
![7DA894BDB4CF2B104915798E6392F3F4](https://user-images.githubusercontent.com/29672485/62093623-89f27c80-b2ac-11e9-97b8-81fb70ab7a4d.jpg)
I don't know what you said "data changes to be saved and loaded as JSON" Is that means text will be loaded with json or the whole widget is using JSON to be saved and loaded.
If it is the former, which matters is that you need to modify that by yourself.

**Comment by zmtzawqlp** [comment]
I counld't get your point. please give more details

**Comment by AlexVincent525** [comment]
Please provide more imformation about your question. :)
