### ISSUE TITLE
I/flutter (10005): 'package:flutter/src/services/text_editing.dart': Failed assertion: line 24 pos 15: 'start != null I/flutter (10005): && start >= -1': is not true.

### ISSUE THREAD

**Issue by CSystem** [fluttercandies/extended_text#26]
I/flutter (10005): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (10005): The following assertion was thrown during paint():
I/flutter (10005): 'package:flutter/src/services/text_editing.dart': Failed assertion: line 24 pos 15: 'start != null
I/flutter (10005): && start >= -1': is not true.
I/flutter (10005):
I/flutter (10005): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (10005): more information in this error message to help you determine and fix the underlying cause.
I/flutter (10005): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (10005):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (10005):
I/flutter (10005): When the exception was thrown, this was the stack:
I/flutter (10005): #2      new TextRange 
package:flutter/…/services/text_editing.dart:24
I/flutter (10005): #3      new TextSelection 
package:flutter/…/services/text_editing.dart:107
I/flutter (10005): #4      ExtendedRenderEditable._getCaretOffset 
package:extended_text_field/src/extended_render_editable.dart:1720
I/flutter (10005): #5      ExtendedRenderEditable._updateSelectionExtentsVisibility 
package:extended_text_field/src/extended_render_editable.dart:284
I/flutter (10005): #6      ExtendedRenderEditable._paintContents 
package:extended_text_field/src/extended_render_editable.dart:1884
I/flutter (10005): #7      ExtendedRenderEditable.paint 
package:extended_text_field/src/extended_render_editable.dart:1968
I/flutter (10005): #8      RenderObject._paintWithContext 
package:flutter/…/rendering/object.dart:2089
I/flutter (10005): #9      PaintingContext.paintChild 
package:flutter/…/rendering/object.dart:172
I/flutter (10005): #10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint 
package:flutter/…/rendering/proxy_box.dart:123
I/flutter (10005): #11     RenderObject._paintWithContext 
package:flutter/…/rendering/object.dart:2089
I/flutter (10005): #12     PaintingContext.paintChild 
package:flutter/…/rendering/object.dart:172
I/flutter (10005): #13     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint 
package:flutter/…/rendering/proxy_box.dart:123
I/flutter (10005): #14     PaintingContext.pushLayer 
package:flutter/…/rendering/object.dart:369
I/flutter (10005): #15     RenderLeaderLayer.paint 
package:flutter/…/rendering/proxy_box.dart:4624
I/flutter (10005): #16     RenderObject._paintWithContext 
package:flutter/…/rendering/object.dart:2089
I/flutter (10005): #17     PaintingContext.paintChild 
package:flutter/…/rendering/object.dart:172
I/flutter (10005): #18     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint 
package:flutter/…/rendering/proxy_box.dart:123
I/flutter (10005): #19     RenderObject._paintWithContext 
package:flutter/…/rendering/object.dart:2089
I/flutter (10005): #20     PaintingContext.paintChild 
package:flutter/…/rendering/object.dart:172
I/flutter (10005): #21     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint 
package:flutter/…/rendering/proxy_box.dart:123
I/flutter (10005): #22     RenderObject._paintWithContext 
package:flutter/…/rendering/object.dart:2089
I/flutter (10005): #23     PaintingContext.paintChild 
package:flutter/…/rendering/object.dart:172
I/flutter (10005): #24     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint 
package:flutter/…/rendering/proxy_box.dart:123

**Comment by zmtzawqlp** [comment]
please provide demo for this issue, and version of extended text
