### ISSUE TITLE
can't reponse tap gesture

### ISSUE THREAD

**Issue by OHeroJ** [fluttercandies/extended_text#3]
```dart
@override
  Widget build(BuildContext context) {
    return Container(
      margin: EdgeInsets.all(10),
      padding: EdgeInsets.all(10),
      color: Colors.white,
      child: StreamBuilder<bool>(
        stream: _cellBloc.isSpread,
        initialData: false,
        builder: (context, snapshot) {
          return snapshot.data ? buildSpreadCell() : buildFoldCell();
        },
      ),
    );
  }

  Widget buildFoldCell() {
    return ExtendedText(
      's我觉得搜jog就搜集公司偶的机构就搜到结构将搜集的工具OS 是的解耦就搜集滚动事件酸豆角构建搜的感觉是家大公鸡搜到过建瓯市就酸豆角构建搜见到过',
      style: TextStyle(fontSize: 16),
      maxLines: 2,
      overFlowTextSpan: OverFlowTextSpan(
        children: [
          TextSpan(
              text: "\u2026 展开",
              style: TextStyle(color: Color(0xff9c9c9c), fontSize: 14),
              recognizer: TapGestureRecognizer()
                ..onTap = () {
                  debugPrint('点击');
                  _mainBloc.addToFolds(widget.data);
                })
        ],
        background: Colors.white,
      ),
    );
  }
 ....
```

when i tap the textspan, the console log

```
flutter: Another exception was thrown: NoSuchMethodError: The getter 'dx' was called on null.
```

**Comment by zmtzawqlp** [comment]
![image](https://user-images.githubusercontent.com/16477333/56110833-7256e880-5f88-11e9-919e-7b813054ec31.png)
使用你的代码没法重现问题，是否更新到最新版本

**Comment by OHeroJ** [comment]
build  for ListView childs

**Comment by zmtzawqlp** [comment]
@OHeroJ  can you provider a simple demo for this issue

**Comment by OHeroJ** [comment]
wait a minutes

**Comment by OHeroJ** [comment]
@zmtzawqlp  https://github.com/OHeroJ/flutter_demo.git

**Comment by OHeroJ** [comment]
> @OHeroJ can you provider a simple demo for this issue


> @zmtzawqlp https://github.com/OHeroJ/flutter_demo.git

Does this problem in the demo？

**Comment by zmtzawqlp** [comment]
@OHeroJ fix with a88c0eab73dc14d8a719f46661f9d82b08e4e05d

**Comment by OHeroJ** [comment]
> @OHeroJ fix with [a88c0ea](https://github.com/fluttercandies/extended_text/commit/a88c0eab73dc14d8a719f46661f9d82b08e4e05d). let me konw if issue is fixed

not happened again , run well.  thank you very mach!

**Comment by OHeroJ** [comment]
Chinese？

**Comment by zmtzawqlp** [comment]
![image](https://user-images.githubusercontent.com/16477333/56116277-ff556e00-5f97-11e9-9e12-043b74dee195.png)
欢迎加入

**Comment by OHeroJ** [comment]
> ![image](https://user-images.githubusercontent.com/16477333/56116277-ff556e00-5f97-11e9-9e12-043b74dee195.png)
> 欢迎加入

被拒，有个回答

**Comment by zmtzawqlp** [comment]
@OHeroJ ....这么简单的问题。。。。dart
