### ISSUE TITLE
如果text的文本是带回车换行的字符串，大概率会出现报错

### ISSUE THREAD

**Issue by cixiu** [fluttercandies/extended_text#4]
如果后台放回的content的格式是如下这种
![image](https://user-images.githubusercontent.com/26104985/56860867-afca6580-69cd-11e9-93d7-2b51c5b1cca6.png)

```dart
ExtendedText(
                      content,
                      maxLines: 3,
                      style: TvStyle.tv_size_28_color_333333,
                      overFlowTextSpan: OverFlowTextSpan(
                        children: <TextSpan>[
                          TextSpan(text: '  \u2026  '),
                          TextSpan(
                            text: "全文",
                            style: TvStyle.tv_size_28_color_5765AD,
                          )
                        ],
                        background: Theme.of(context).canvasColor,
                      ),
                    ),
```

报错信息：

![image](https://user-images.githubusercontent.com/26104985/56860644-65e08000-69cb-11e9-853e-aac2d22e350f.png)

**Comment by zmtzawqlp** [comment]
@cixiu 是最新版本吗。。能否提供一下 能重现bug的demo。

**Comment by cixiu** [comment]
@zmtzawqlp 公司后端 api 返回的数据（如上所说的格式）确实会出现上述错误，自己手写的换行字符串则不会出现这个错误，一时间我还真没法复现这个bug呢

**Comment by zmtzawqlp** [comment]
@cixiu 你把公司的那个字符串copy出来。写在demo里面。不然很难去调试问题呢

**Comment by cixiu** [comment]
@zmtzawqlp 我试过将字段copy出来，例如：`仿谷歌搜灭霸彩蛋特效代码↵↵↵↵代码` copy成 `仿谷歌搜灭霸彩蛋特效代码\n\n\n\n代码`则没问题，直接用 api 字段就有问题😂

明天去公司再看看吧😂

**Comment by zmtzawqlp** [comment]
@cixiu 嗯嗯。不知道是不是你那个字符的问题。。↵↵↵↵ 就会有问题？

**Comment by cixiu** [comment]
@zmtzawqlp ![](https://user-images.githubusercontent.com/26104985/56860867-afca6580-69cd-11e9-93d7-2b51c5b1cca6.png) 里的↵字符，就是换行符，可是不知为何会出错

**Comment by zmtzawqlp** [comment]
@cixiu 进群聊吧。就是这个字符在里面就会报错？ 这个报错是指，自定的溢出文本如果大于一行，我就没法做处理了
![image](https://user-images.githubusercontent.com/16477333/56872422-6fb1c400-6a5b-11e9-9942-78c43c87c9c8.png)

**Comment by cixiu** [comment]
@zmtzawqlp 已加 同意下

**Comment by zmtzawqlp** [comment]
@cixiu 不是回答问题吗

**Comment by cixiu** [comment]
![image](https://user-images.githubusercontent.com/26104985/56874653-fcfe1400-6a6d-11e9-9c41-f492ca072d4d.png)

**Comment by zmtzawqlp** [comment]
无法重现
