### ISSUE TITLE
关于富文本嵌套的问题

### ISSUE THREAD

**Issue by niuxinhuai** [fluttercandies/extended_text#41]
eg: #皮卡丘[emoji]#
请问关于这种嵌套的富文本，我应该如何处理，才可以即让“皮卡丘”文字变色，又可以让[emoji]显示表情？

**Comment by zmtzawqlp** [comment]
#皮卡丘#[emoji] 这样不可以吗？？  或者##  拿到之后。你在对里面的内容进行解析。。整个有widgespan

**Comment by niuxinhuai** [comment]
我最近在仿写其他的App，看到里边的富文本是这种形式的#皮卡丘[emoji]#这种样式的，当我使用这个三方的时候，有单独处理#和[这两个特殊符号，但是当他们在一起嵌套的时候，却没办法两个共同出现，因此我想问问有没有什么办法，可以实现二者结合，当然如果您能给我一个实现的Demo最好啦。谢谢------------------ 原始邮件 ------------------
发件人: "zmtzawqlp"<notifications@github.com>
发送时间: 2019年11月7日(星期四) 晚上6:50
收件人: "fluttercandies/extended_text"<extended_text@noreply.github.com>;
抄送: "MaKuru"<1242537720@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [fluttercandies/extended_text] 关于富文本嵌套的问题 (#41)



#皮卡丘#[emoji] 这样不可以吗？？  或者##  拿到之后。你在对里面的内容进行解析。。整个有widgespan
 
&mdash;

**Comment by zmtzawqlp** [comment]
## 判断这个。 获取到 皮卡丘[emoji]  然后再对这个字符串进行解析。 使用WidgetSpan创建内容
