### ISSUE TITLE
关于文本长按复制全选功能，长按文本时，文本背景显示的问题

### ISSUE THREAD

**Issue by gejianmin** [fluttercandies/extended_text#43]
一、长按时必须用力长按才能唤起弹出菜单
二、如果文本长度是一个字符的话，无论是长按还是双击，很难唤起弹出菜单
三、长按后，选中的文本背景高度不一致,如下图
<img width="195" alt="截屏2019-11-27下午5 19 17" src="https://user-images.githubusercontent.com/20701256/69710945-33eaf400-113b-11ea-9e63-58bd87cb81b8.png">
 （作者可以在百忙之中，抽空优化一下）

**Comment by zmtzawqlp** [comment]
as design
