### ISSUE TITLE
ExtendedText.rich是否可以考虑增加strutStyle属性？

### ISSUE THREAD

**Issue by cixiu** [fluttercandies/extended_text#5]
`Text.rich()` 中的 `strutStyle` 可以用来控制文字的行高，特别是对于中文字符来说这是一个很有用的属性。`ExtendedText.rich()` 暂时缺少这个属性，是否考虑增加一下呢？

**Comment by zmtzawqlp** [comment]
没法支持，如果支持了。你的图片，或者特殊文字就会出问题，，你要控制行高，可以在builder里面给textspan的style设置呢。。

**Comment by zmtzawqlp** [comment]
因为图片支持设置高度宽度的，

**Comment by cixiu** [comment]
@zmtzawqlp 感谢。通过 style 的 height 属性确实也是可以控制行高的，只是通过height计算得来的行高具体是多少是个谜。

**Comment by zmtzawqlp** [comment]
![image](https://user-images.githubusercontent.com/16477333/57848542-be0ce400-780b-11e9-8a95-606e8cbbf6d7.png)

strutStyle  里面的效果也是一样的哦。。没明白有啥区别？

**Comment by cixiu** [comment]
如果fontSize: 20.0, height: 1.0, 但是在视图上看到的文字所占的高度是大于 20.0。

**Comment by zmtzawqlp** [comment]
字体大小又不等于高度。。不同字体还有区别，你直接加群吧。。说出你的需求是啥。。你可以进入误区了

**Comment by cixiu** [comment]
@zmtzawqlp 应该是的。我把字体的大小理解成高度了。再次感谢，我已经加过你的群里哦~~
