### ISSUE TITLE
Click outside of extended text raises exception

### ISSUE THREAD

**Issue by ControlAdad** [fluttercandies/extended_text#58]
The following assertion was thrown while handling a gesture:
Looking up a deactivated widget's ancestor is unsafe.

At this point the state of the widget's element tree is no longer stable.

To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

When the exception was thrown, this was the stack: 
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:3508:9)
#1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:3522:6)
#2      Element.findAncestorStateOfType (package:flutter/src/widgets/framework.dart:3641:12)
#3      Overlay.of (package:flutter/src/widgets/overlay.dart:237:41)
#4      ExtendedTextSelectionOverlay.showToolbar (package:extended_text_library/src/selection/extended_text_selection_overlay.dart:193:13)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#af7cb
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(38.8, 23.6)
  button: 1
  sent tap down

**Comment by zmtzawqlp** [comment]
flutter version

**Comment by zmtzawqlp** [comment]
please provide， version of extended text and flutter, and a demo

**Comment by MynamesHai** [comment]
In class ExtendedTextSelectionOverlay;

void showToolbar() {
    assert(_toolbar == null);          ------> This is exception (Failed assertion: line 202 pos 12: '_toolbar == null': is not true.)
    _toolbar = OverlayEntry(builder: _buildToolbar);
    Overlay.of(context, rootOverlay: true, debugRequiredFor: debugRequiredFor)
        .insert(_toolbar);
    _toolbarController.forward(from: 0.0);
  }
