### ISSUE TITLE
Long press on iOS for Extended Text Selection

### ISSUE THREAD

**Issue by hovermouse** [fluttercandies/extended_text#62]
Hi - is there a way to implement long press for the Selection Menu on iOS? Currently I have long press on Android but need to double click for iOS which users are not discovering.  
Thanks for the great plugin by the way!

**Comment by zmtzawqlp** [comment]
fork and change by your self,  it is the rule design by google

**Comment by hovermouse** [comment]
Hi - Sorry, a bit confused where in the code this is occurring.  When I use a Flutter TextField (actually a TextFormField) the long press works for iOS but it doesn't when I use ExtendedText so where is the google design rule happening? Can you give me some pointers? I think the implementation is in extended_text_library but I'm looping around CommonTextSelectionGestureDetectorBuilder and ExtendedTextSelectionGestureDetectorBuilderDelegate and I can't see how showToolbar is called?  Thanks!

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_text_library/blob/cd96c458a8871d58282cee5292712cd69572b372/lib/src/selection/extended_text_selection.dart#L400   

this code is from v1.12.13+hotfix.5,  if you find they are changed from official, you can fork it and change they at your side.  i only maintain for stable flutter version。

**Comment by hovermouse** [comment]
Ok - thanks for the info, I'll have  poke around in there!

Regards

**Comment by MeandNi** [comment]
https://github.com/flutter/flutter/blob/680a7bc8e8ca59818e6e21f55a9e64f6640d5467/packages/flutter/lib/src/material/selectable_text.dart#L102

@zmtzawqlp 这部分官方似乎已经不对平台做特殊处理了。

**Comment by zmtzawqlp** [comment]
> https://github.com/flutter/flutter/blob/680a7bc8e8ca59818e6e21f55a9e64f6640d5467/packages/flutter/lib/src/material/selectable_text.dart#L102
> 
> @zmtzawqlp 这部分官方似乎已经不对平台做特殊处理了。

嗯嗯。下个版本再merge 下。代码不好merge了
