### ISSUE TITLE
有没有办法不用WidgetSpan实现点击效果

### ISSUE THREAD

**Issue by zhengbomo** [fluttercandies/extended_text#75]
不用widgetSpan实现点击高亮的效果，例如点击改变文字背景色，类似FlatButton

**Comment by zmtzawqlp** [comment]
可以但是没必要。普通文本也有点击事件

**Comment by zhengbomo** [comment]
> 可以但是没必要。普通文本也有点击事件

默认的点击事件没有高亮效果

**Comment by zmtzawqlp** [comment]
setstate。然后比如解析<b 文字 >为高亮文字
