### ISSUE TITLE
遇到'\r'为单独一行时，选中框偏移，全选模式菜单位置不对

### ISSUE THREAD

**Issue by v7lin** [fluttercandies/extended_text#80]
![Screenshot_20200915_210829_com yuedu reader](https://user-images.githubusercontent.com/8845083/93214370-acd53e00-f797-11ea-9b2c-1972cffa53dc.jpg)

**Comment by zmtzawqlp** [comment]
替换成 \n呢？？ 这个是官方计算的位置

**Comment by v7lin** [comment]
我尝试了，换成'\n'会多出空行，空行也有这个问题，这是全角和半角的问题引发的。计算选中光标的方法有问题

**Comment by v7lin** [comment]
同14号字体，汉语字符的行高是20，英语字符的行高是16，textPainter.preferredLineHeight=16。而我看了选中框的计算方式是直接使用textPainter.preferredLineHeight当成了行高，这小于真实的行高。

**Comment by zmtzawqlp** [comment]
可以给官方提下issue

**Comment by v7lin** [comment]
[flutter issues#65905](https://github.com/flutter/flutter/issues/65905)

**Comment by zmtzawqlp** [comment]
试试 selectionHeightMode

**Comment by v7lin** [comment]
flutter 1.22.1 上已修复
