### ISSUE TITLE
Paragraph Style Text Rendering after image.

### ISSUE THREAD

**Issue by canewsin** [fluttercandies/extended_text#81]
How can i write text like below
![Capture](https://user-images.githubusercontent.com/26790557/93713396-3e1e2900-fb79-11ea-97f2-b16a3ea46d67.PNG)

i.e from top of the image and want to continue text below image, if we have more text

**Comment by zmtzawqlp** [comment]
flutter sdk is not support, i think may be you should use markdown/html widget
