### ISSUE TITLE
EndFlag 不支持多个字符

### ISSUE THREAD

**Issue by lijy91** [fluttercandies/extended_text#89]
如果我需要把 `{{@` 和 '}}' 作为 开始和结束符，现在则只会反最后一个字符当作识别符。

```
Test {{@extended_text}}  Custom SpecialText.
```

**Comment by zmtzawqlp** [comment]
如果把文本转换成textspan本身就不是组件应该做的事情，你完全可以自己按照自己的方式进行解析，demo只是demo
