### ISSUE TITLE
this widget makes gestureDetector don't work

### ISSUE THREAD

**Issue by FitzMusk** [fluttercandies/extended_text#90]
1. this widget makes gestureDetector don't work. Like when I want to longPress on a selectable text by gestureDetector, it won't work.

Looking forward to you reply. Thanks in advance.

**Comment by zmtzawqlp** [comment]
longPress is handled inside

**Comment by FitzMusk** [comment]
didn't find it😭😭😭

**Comment by FitzMusk** [comment]
![7D697B232EA43B615F1D4237096B17F2](https://user-images.githubusercontent.com/43529681/103056736-b8c36e00-45d8-11eb-860a-3b140972cd24.jpg)

**Comment by FitzMusk** [comment]
I solved last problem by l10n config. And  when I longpress on the text by SelectableText widget, the text can be selected. But when I use ExtendedText, it doesn't response.
