### ISSUE TITLE
[Help] How to properly override 'onTapUp' method for text?

### ISSUE THREAD

**Issue by emvaized** [fluttercandies/extended_text#91]
To be more precise - I want to get 'TapUpDetails' in my 'onTap()' callback, provided to `ExtendedText.rich`.

![Screenshot_20201229_222724](https://user-images.githubusercontent.com/37851576/103312228-0bf84f00-4a25-11eb-838f-075151e063e2.png)

`extended_text_library-4.03/lib/src/selection/extended-text-selection.dart/CommonTextSelectionGestureDetectorBuilder`
![2020-12-29_22-24](https://user-images.githubusercontent.com/37851576/103312174-e3705500-4a24-11eb-8171-a050371c54ab.png)

I saw the `ExtendedTextSelectionGestureDetectorBuilder` class in the same file, which has overridable method for this, but didn't find any documentation on how to use it
![Screenshot_20201229_223231](https://user-images.githubusercontent.com/37851576/103312444-bf614380-4a25-11eb-9042-41df29a57415.png)

Thanks

**Comment by zmtzawqlp** [comment]
What is the purpose ？

**Comment by emvaized** [comment]
@zmtzawqlp 
I wrapped my Scaffold body in `GestureDetector` to play some animations depending on user tap coordinates, and `ExtendedText.rich` seems to absorb tap events, causing my code not execute.
So I wanted to provide the same callback to text widget, but didn't found how to get coordinates from tap on text

**Comment by zmtzawqlp** [comment]
you can use a widgetspan
