### ISSUE TITLE
mac M1 芯片，flutter2.0.0 报错has fewer positional arguments than those of overridden method

### ISSUE THREAD

**Issue by zhouzongfu** [fluttercandies/extended_text#95]
mac M1 芯片，flutter2.0.0 报错
Performing hot restart...
Syncing files to device iPhone 12 Pro Max...
../../sdk/.pub-cache/hosted/pub.flutter-io.cn/extended_text_library-4.0.3/lib/src/selection/cupertino_text_selection_controls.dart:483:10: Error: The method 'ExtendedCupertinoTextSelectionControls.buildToolbar' has fewer positional arguments than those of overridden method 'TextSelectionControls.buildToolbar'.
  Widget buildToolbar(
         ^
../../sdk/packages/flutter/lib/src/widgets/text_selection.dart:137:10: Context: This is the overridden method ('buildToolbar').
  Widget buildToolbar(
         ^
../../sdk/.pub-cache/hosted/pub.flutter-io.cn/extended_text_library-4.0.3/lib/src/selection/material_text_selection_controls.dart:762:10: Error: The method 'ExtendedMaterialTextSelectionControls.buildToolbar' has fewer positional arguments than those of overridden method 'TextSelectionControls.buildToolbar'.
  Widget buildToolbar(
         ^
../../sdk/packages/flutter/lib/src/widgets/text_selection.dart:137:10: Context: This is the overridden method ('buildToolbar').
  Widget buildToolbar(
         ^
../../sdk/.pub-cache/hosted/pub.flutter-io.cn/extended_text_field-5.0.4/lib/src/extended_text_field.dart:872:32: Error: No named parameter with the name 'nullOk'.
        MediaQuery.of(context, nullOk: true)?.navigationMode ??
                               ^^^^^^
../../sdk/packages/flutter/lib/src/widgets/media_query.dart:818:25: Context: Found this candidate, but the arguments don't match.
  static MediaQueryData of(BuildContext context) {
                        ^^
../../sdk/.pub-cache/hosted/pub.flutter-io.cn/extended_text_library-4.0.3/lib/src/selection/extended_text_selection_overlay.dart:348:46: Error: Too few positional arguments: 8 required, 7 given.
        child: selectionControls.buildToolbar(
                                             ^
../../sdk/.pub-cache/hosted/pub.flutter-io.cn/extended_text-4.1.0/lib/src/extended_rich_text.dart:166:13: Error: No named parameter with the name 'nullOk'.
            nullOk: true,
            ^^^^^^
../../sdk/packages/flutter/lib/src/widgets/localizations.dart:413:17: Context: Found this candidate, but the arguments don't match.
  static Locale localeOf(BuildContext context) {
                ^^^^^^^^
../../sdk/.pub-cache/hosted/pub.flutter-io.cn/extended_text-4.1.0/lib/src/extended_rich_text.dart:196:60: Error: No named parameter with the name 'nullOk'.
      ..locale = locale ?? Localizations.localeOf(context, nullOk: true)
                                                           ^^^^^^
../../sdk/packages/flutter/lib/src/widgets/localizations.dart:413:17: Context: Found this candidate, but the arguments don't match.
  static Locale localeOf(BuildContext context) {
                ^^^^^^^^
../../sdk/.pub-cache/hosted/pub.flutter-io.cn/extended_text_field-5.0.4/lib/src/extended_editable_text.dart:2694:57: Error: No named parameter with the name 'nullOk'.
      locale: locale ?? Localizations.localeOf(context, nullOk: true),
                                                        ^^^^^^
../../sdk/packages/flutter/lib/src/widgets/localizations.dart:413:17: Context: Found this candidate, but the arguments don't match.
  static Locale localeOf(BuildContext context) {
                ^^^^^^^^
../../sdk/.pub-cache/hosted/pub.flutter-io.cn/extended_text_field-5.0.4/lib/src/extended_editable_text.dart:2741:60: Error: No named parameter with the name 'nullOk'.
      ..locale = locale ?? Localizations.localeOf(context, nullOk: true)
                                                           ^^^^^^
../../sdk/packages/flutter/lib/src/widgets/localizations.dart:413:17: Context: Found this candidate, but the arguments don't match.
  static Locale localeOf(BuildContext context) {
                ^^^^^^^^
../../sdk/.pub-cache/hosted/pub.flutter-io.cn/flutter_svg-0.19.1/lib/src/picture_provider.dart:52:59: Error: No named parameter with the name 'nullOk'.
        context != null ? Localizations.localeOf(context, nullOk: true) : null,
                                                          ^^^^^^
../../sdk/packages/flutter/lib/src/widgets/localizations.dart:413:17: Context: Found this candidate, but the arguments don't match.
  static Locale localeOf(BuildContext context) {
                ^^^^^^^^
Restarted application in 1,493ms.

**Comment by zmtzawqlp** [comment]
5.0.0 is ready on pub.dev
